apiVersion: v1
kind: Template
metadata: {}
objects:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: ha-webserver50-tomcat9
    name: ha-webserver50-tomcat9
  spec:
    replicas: 1
    selector:
      app: ha-webserver50-tomcat9
      deploymentconfig: ha-webserver50-tomcat9
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: ha-webserver50-tomcat9
          deploymentconfig: ha-webserver50-tomcat9
      spec:
        containers:
        - image: ' '
          name: jboss
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          - containerPort: 8778
            protocol: TCP
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - jboss
        from:
          kind: ImageStreamTag
          name: webserver50-tomcat9-openshift:1.2-13
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: ha-webserver50-tomcat9
    name: ha-webserver50-tomcat9
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
    selector:
      deploymentconfig: ha-webserver50-tomcat9
  status:
    loadBalancer: {}
